[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/recipes"
  to = "/.netlify/functions/getRecipes"
  status = 200
  force = true

[[redirects]]
  from = "/api/recipes/:id/information"
  to = "/.netlify/functions/getRecipeInformation?id=:id"
  status = 200
  force = true